export * from './roles';
export * from './visitor';
export * from './visitor-blacklist';
export * from './recurring-pass';
export * from './phone';
export * from './walk-in-owner';
export * from './unit-search';
export * from './billing';
export * from './einvoice';
export * from './defect';
export * from './handover';
export * from './announcement';
export * from './polls';
export * from './governance';
export * from './facility';
export * from './parcel';
export * from './safety';
export * from './mcp';
export * from './upload';
export * from './setup';
export * from './forms';
export * from './documents';
export * from './lost-found';
export * from './whatsapp';
export * from './platform';

export const APP_NAME = 'SmartResidence';
export const APP_DEEPLINK_SCHEME = 'smartresidence';
