import { z } from 'zod';

/**
 * Image mime types accepted by the upload pipeline.
 *
 * `image/heic` / `image/heif` are included because iOS captures and iCloud
 * library exports are HEIC by default. Mobile clients convert HEIC -> JPEG
 * before upload; web stores the original (iOS Safari already hands us JPEG
 * when picking from the album, desktop HEIC is stored as-is).
 */
export const ALLOWED_IMAGE_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'image/heic',
  'image/heif',
] as const;
export type AllowedImageMimeType = (typeof ALLOWED_IMAGE_MIME_TYPES)[number];

/** Maximum size for a single uploaded image (15 MB). */
export const MAX_UPLOAD_BYTES = 15 * 1024 * 1024;

/** Maximum size for a single uploaded PDF document (25 MB). */
export const MAX_DOCUMENT_UPLOAD_BYTES = 25 * 1024 * 1024;

export const ALLOWED_DOCUMENT_MIME_TYPES = ['application/pdf'] as const;
export type AllowedDocumentMimeType = (typeof ALLOWED_DOCUMENT_MIME_TYPES)[number];

/** How many attachments a single message / form may carry. */
export const MAX_ATTACHMENTS_PER_MESSAGE = 6;

/** Max combined size of a single message's attachments (40 MB). */
export const MAX_TOTAL_UPLOAD_BYTES = 40 * 1024 * 1024;

/** Longest edge (px) the optimized full image is downscaled to server-side. */
export const IMAGE_MAX_DIMENSION = 1600;

/** Longest edge (px) of the generated thumbnail derivative. */
export const THUMBNAIL_MAX_DIMENSION = 400;

/** TTL (hours) after which an un-attached (PENDING) upload is swept. */
export const ORPHAN_ATTACHMENT_TTL_HOURS = 24;

/** Lifecycle status of an attachment. */
export type AttachmentStatus = 'PENDING' | 'COMMITTED';

//////////////////////////////////////////////////////////////////////////////
// Output (delivery) formats & transcode pipeline (AVIF + WebP fallback)
//////////////////////////////////////////////////////////////////////////////

/**
 * Delivery image formats the server emits per upload. `avif` is the primary,
 * smallest format; `webp` is the universal fallback for AVIF-incapable clients
 * (pre-16.4 Safari, legacy Android WebView, managed Edge 118–120).
 */
export const OUTPUT_IMAGE_FORMATS = ['avif', 'webp'] as const;
export type OutputImageFormat = (typeof OUTPUT_IMAGE_FORMATS)[number];

/** Primary delivery format requested by capable clients. */
export const DEFAULT_OUTPUT_FORMAT: OutputImageFormat = 'avif';

/** Fallback delivery format served when AVIF is missing / unsupported. */
export const FALLBACK_OUTPUT_FORMAT: OutputImageFormat = 'webp';

/** MIME type for each output format. */
export const OUTPUT_FORMAT_MIME: Record<OutputImageFormat, string> = {
  avif: 'image/avif',
  webp: 'image/webp',
};

export function isOutputImageFormat(v: string | null | undefined): v is OutputImageFormat {
  if (!v) return false;
  return (OUTPUT_IMAGE_FORMATS as readonly string[]).includes(v.toLowerCase());
}

/** The four derivative variants produced per (non-passthrough) image upload. */
export const VARIANT_KINDS = ['displayAvif', 'thumbAvif', 'displayWebp', 'thumbWebp'] as const;
export type VariantKind = (typeof VARIANT_KINDS)[number];

/**
 * Lifecycle of the async (BullMQ) transcode pipeline for an attachment:
 * - `PENDING`  — row created; full variant set still being generated by the worker.
 * - `READY`    — AVIF + WebP variant set generated; original deleted.
 * - `FAILED`   — transcode threw irrecoverably; original (or inline thumb) retained.
 * - `SKIPPED`  — passthrough (GIF) or a decode the host can't handle (HEIC w/o libheif);
 *                original bytes are served as-is.
 */
export const TRANSCODE_STATUSES = ['PENDING', 'READY', 'FAILED', 'SKIPPED'] as const;
export type TranscodeStatus = (typeof TRANSCODE_STATUSES)[number];

/**
 * LOCKED encode parameters (Phase 1). Metadata is preserved on derivatives
 * (`.withMetadata()`) because originals are discarded — derivatives are the
 * only copy.
 */
export const AVIF_DISPLAY_OPTS = { quality: 50, effort: 4, chromaSubsampling: '4:2:0' } as const;
export const AVIF_THUMB_OPTS = { quality: 45, effort: 4, chromaSubsampling: '4:2:0' } as const;
export const WEBP_DISPLAY_OPTS = { quality: 80 } as const;
export const WEBP_THUMB_OPTS = { quality: 70 } as const;

/**
 * RAW input class (CR2/CR3/NEF/ARW/DNG) is a Phase 2 feature — OFF in Phase 1.
 * Left here so the queue / variant model can branch on it later behind a flag.
 */
export const RAW_INPUT_ENABLED = false;
export const ALLOWED_RAW_MIME_TYPES: readonly string[] = [];

/**
 * Magic-byte sniff of the leading bytes of a file. Returns the detected MIME
 * type (one of the allowed image/document types) or `null` if unrecognized.
 * Defends against Content-Type spoofing — the declared MIME is never trusted
 * on its own. Operates on a plain byte view so it is reusable + unit-testable.
 */
export function sniffMimeType(bytes: Uint8Array): string | null {
  const b = bytes;
  if (b.length < 12) return null;

  // JPEG: FF D8 FF
  if (b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff) return 'image/jpeg';

  // PNG: 89 50 4E 47 0D 0A 1A 0A
  if (
    b[0] === 0x89 &&
    b[1] === 0x50 &&
    b[2] === 0x4e &&
    b[3] === 0x47 &&
    b[4] === 0x0d &&
    b[5] === 0x0a &&
    b[6] === 0x1a &&
    b[7] === 0x0a
  ) {
    return 'image/png';
  }

  // GIF: "GIF87a" / "GIF89a"
  if (b[0] === 0x47 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x38) return 'image/gif';

  // PDF: "%PDF-"
  if (b[0] === 0x25 && b[1] === 0x50 && b[2] === 0x44 && b[3] === 0x46 && b[4] === 0x2d) {
    return 'application/pdf';
  }

  // RIFF....WEBP (WebP)
  if (
    b[0] === 0x52 &&
    b[1] === 0x49 &&
    b[2] === 0x46 &&
    b[3] === 0x46 &&
    b[8] === 0x57 &&
    b[9] === 0x45 &&
    b[10] === 0x42 &&
    b[11] === 0x50
  ) {
    return 'image/webp';
  }

  // ISO-BMFF "ftyp" box (HEIC/HEIF) — brand at bytes 8..12.
  if (b[4] === 0x66 && b[5] === 0x74 && b[6] === 0x79 && b[7] === 0x70) {
    const brand = String.fromCharCode(
      b[8] ?? 0,
      b[9] ?? 0,
      b[10] ?? 0,
      b[11] ?? 0,
    ).toLowerCase();
    const heicBrands = new Set([
      'heic',
      'heix',
      'heim',
      'heis',
      'hevc',
      'hevx',
      'hevm',
      'hevs',
      'mif1',
      'msf1',
    ]);
    if (heicBrands.has(brand)) {
      // mif1/msf1 are generic HEIF containers; report image/heif for those.
      return brand === 'mif1' || brand === 'msf1' ? 'image/heif' : 'image/heic';
    }
  }

  return null;
}

/** HTML `accept` value for native file inputs (web). */
export const IMAGE_ACCEPT_ATTR = 'image/*,.heic,.heif';

/** HTML `accept` value for PDF uploads (announcement attachments). */
export const DOCUMENT_ACCEPT_ATTR = 'application/pdf,.pdf';

export function isAllowedImageMime(mime: string | null | undefined): mime is AllowedImageMimeType {
  if (!mime) return false;
  return (ALLOWED_IMAGE_MIME_TYPES as readonly string[]).includes(mime.toLowerCase());
}

export function isAllowedDocumentMime(
  mime: string | null | undefined,
): mime is AllowedDocumentMimeType {
  if (!mime) return false;
  return (ALLOWED_DOCUMENT_MIME_TYPES as readonly string[]).includes(mime.toLowerCase());
}

export function isHeic(mime: string | null | undefined): boolean {
  if (!mime) return false;
  const m = mime.toLowerCase();
  return m === 'image/heic' || m === 'image/heif';
}

/** Strip path separators / odd characters so the storage key stays clean. */
export function sanitizeFileName(name: string): string {
  const base = name.split(/[\\/]/).pop() ?? name;
  const cleaned = base.replace(/[^A-Za-z0-9._-]+/g, '-').replace(/-+/g, '-');
  const trimmed = cleaned.replace(/^[-.]+/, '').slice(-120);
  return trimmed.length > 0 ? trimmed : 'upload';
}

/** Contract for the presign request body (`POST /api/attachments/presign`). */
export const PresignUploadSchema = z.object({
  contentType: z.string().min(1).max(120),
  fileName: z.string().min(1).max(200),
  size: z.number().int().positive().max(MAX_UPLOAD_BYTES).optional(),
});
export type PresignUploadInput = z.infer<typeof PresignUploadSchema>;

/** Response returned by the presign endpoint. */
export interface PresignUploadResponse {
  url: string;
  fields: Record<string, string>;
  bucket: string;
  key: string;
  expiresIn: number;
  attachmentId: string;
}

/**
 * Response from the multipart upload endpoint (`POST /api/uploads`). The
 * server has already optimized the image + generated a thumbnail; the raw
 * phone photo is never stored.
 */
export interface UploadResponse {
  attachmentId: string;
  key: string;
  thumbnailKey: string | null;
  mimeType: string;
  size: number;
  width: number | null;
  height: number | null;
  status: AttachmentStatus;
  /** Primary delivery format of the (eventual) variant set, e.g. `'avif'`. */
  format: string | null;
  /** Async transcode lifecycle — `PENDING` until the worker finishes. */
  transcodeStatus: TranscodeStatus;
}

/** A successfully uploaded attachment, as referenced by forms/messages. */
export interface UploadedAttachment {
  attachmentId: string;
  key: string;
  thumbnailKey?: string | null;
  mimeType: string;
  size: number;
  width?: number | null;
  height?: number | null;
  /** Local preview URL/URI (object URL on web, file uri on mobile). */
  previewUrl?: string;
  fileName?: string;
}
