import type { PrismaService } from '@/prisma/prisma.service';
import { describe, expect, it, vi } from 'vitest';
import { BillingAutomationService } from './billing-automation.service';
import type { BillingService } from './billing.service';
import type { FeeScheduleService } from './fee-schedule.service';

const CONDO = 'condo-1';

function makeService(opts: {
  settings?: Record<string, unknown>;
  units?: Array<{ id: string }>;
  existing?: Array<{ unitId: string }>;
  generated?: { created: number; skipped: number; skippedNoRate: number; units: number };
}) {
  const settings = {
    billingAutomation: {
      enabled: true,
      generationDay: 1,
      periodStrategy: 'NEXT_MONTH',
      dueStrategy: 'DAY_OF_MONTH',
      dueDay: 15,
      dueOffsetDays: 14,
      ...opts.settings,
    },
  };
  const prisma = {
    condo: {
      findUnique: vi.fn(async () => ({ id: CONDO, settings })),
      update: vi.fn(async () => ({})),
    },
    unit: {
      findMany: vi.fn(async () => opts.units ?? [{ id: 'unit-1' }, { id: 'unit-2' }]),
    },
    invoice: {
      findMany: vi.fn(async () => opts.existing ?? []),
    },
    auditLog: {
      create: vi.fn(async () => ({})),
    },
    $transaction: vi.fn(async (ops: Array<Promise<unknown>>) => Promise.all(ops)),
  } as unknown as PrismaService;
  const billing = {
    generateRecurring: vi.fn(
      async () => opts.generated ?? { created: 2, skipped: 0, skippedNoRate: 0, units: 2 },
    ),
  } as unknown as BillingService;
  const feeSchedule = {
    computeLinesForUnit: vi.fn(() => [
      { code: 'MAINT', description: 'Monthly maintenance fee', unitPrice: 100, quantity: 1 },
    ]),
  } as unknown as FeeScheduleService;
  const automations = {
    startSystemRun: vi.fn(async () => ({ id: 'run-1' })),
    startRun: vi.fn(async () => ({ id: 'run-1' })),
    finishRun: vi.fn(async () => ({ id: 'run-1' })),
    failRun: vi.fn(async () => ({ id: 'run-1' })),
  };
  const service = new BillingAutomationService(prisma, billing, feeSchedule, automations as never);
  return { service, prisma, billing, feeSchedule, automations };
}

describe('BillingAutomationService.calculateWindow', () => {
  it('calculates next-month period and clamps due day to the month end', () => {
    const { service } = makeService({
      settings: { generationDay: 31, dueDay: 31 },
    });

    const window = service.calculateWindow(
      {
        enabled: true,
        generationDay: 31,
        periodStrategy: 'NEXT_MONTH',
        dueStrategy: 'DAY_OF_MONTH',
        dueDay: 31,
        dueOffsetDays: 14,
      },
      new Date('2026-01-31T02:00:00.000Z'),
    );

    expect(window.runOnOrAfter.toISOString()).toBe('2026-01-31T00:00:00.000Z');
    expect(window.periodStart.toISOString()).toBe('2026-02-01T00:00:00.000Z');
    expect(window.periodEnd.toISOString()).toBe('2026-02-28T23:59:59.999Z');
    expect(window.dueDate.toISOString()).toBe('2026-02-28T23:59:59.999Z');
  });
});

describe('BillingAutomationService.runCondo', () => {
  it('dry-runs without creating invoices', async () => {
    const { service, billing } = makeService({});

    const result = await service.runCondo(null, CONDO, {
      dryRun: true,
      now: new Date('2026-06-01T00:00:00.000Z'),
      requireDue: true,
      trigger: 'scheduled',
    });

    expect(result).toMatchObject({ dryRun: true, wouldCreate: 2, created: 0 });
    expect(billing.generateRecurring).not.toHaveBeenCalled();
  });

  it('runs due automation through duplicate-safe recurring generation', async () => {
    const { service, billing, prisma } = makeService({});

    const result = await service.runCondo(null, CONDO, {
      now: new Date('2026-06-01T00:00:00.000Z'),
      requireDue: true,
      trigger: 'scheduled',
    });

    expect(result.created).toBe(2);
    expect(billing.generateRecurring).toHaveBeenCalledWith(
      null,
      CONDO,
      expect.objectContaining({
        periodStart: new Date('2026-07-01T00:00:00.000Z'),
        periodEnd: new Date('2026-07-31T23:59:59.999Z'),
        dueDate: new Date('2026-07-15T23:59:59.999Z'),
      }),
      expect.objectContaining({
        skipAuthorization: true,
        metadata: expect.objectContaining({
          autoGenerated: true,
          automation: true,
          automationTrigger: 'scheduled',
        }),
      }),
    );
    expect(prisma.auditLog.create).toHaveBeenCalled();
  });

  it('skips generation when all billable units already have the period', async () => {
    const { service, billing } = makeService({
      existing: [{ unitId: 'unit-1' }, { unitId: 'unit-2' }],
    });

    const result = await service.runCondo(null, CONDO, {
      now: new Date('2026-06-01T00:00:00.000Z'),
      requireDue: true,
      trigger: 'scheduled',
    });

    expect(result.skipReason).toBe('already_generated');
    expect(result.created).toBe(0);
    expect(billing.generateRecurring).not.toHaveBeenCalled();
  });
});
